const dummyAgents: Array<Agent> = [
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar1.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: 86.7,
    currentPnl: 86.7,
    name: "Yardsticker",
    token: {
      agentId: "1",
      name: "Liquiditer",
      symbol: "A1",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 100_000,
    winRate: 100,
    active: true,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar2.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: -20.43,
    currentPnl: -20.43,
    name: "Greenmonger",
    token: {
      agentId: "2",
      name: "Agent 2",
      symbol: "A2",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 5400,
    winRate: 100,
    active: false,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar3.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: 90.5,
    currentPnl: 90.5,
    name: "Liquiditer",
    token: {
      agentId: "3",
      name: "Agent 3",
      symbol: "A3",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 12_789,
    winRate: 100,
    active: false,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar4.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: -12.6,
    currentPnl: -12.6,
    name: "Njoku",
    token: {
      agentId: "4",
      name: "Benjamin Bills",
      symbol: "A4",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 600,
    winRate: 100,
    active: true,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar1.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: 86.7,
    currentPnl: 86.7,
    name: "Yardsticker",
    token: {
      agentId: "1",
      name: "Liquiditer",
      symbol: "A1",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 100_000,
    winRate: 100,
    active: true,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar2.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: -20.43,
    currentPnl: -20.43,
    name: "Greenmonger",
    token: {
      agentId: "2",
      name: "Agent 2",
      symbol: "A2",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 5400,
    winRate: 100,
    active: false,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar3.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: 90.5,
    currentPnl: 90.5,
    name: "Liquiditer",
    token: {
      agentId: "3",
      name: "Agent 3",
      symbol: "A3",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 12_789,
    winRate: 100,
    active: false,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar4.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: -12.6,
    currentPnl: -12.6,
    name: "Njoku",
    token: {
      agentId: "4",
      name: "Benjamin Bills",
      symbol: "A4",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 600,
    winRate: 100,
    active: true,
  },
  {
    creator: {
      username: "Beethoven",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar4.png",
      profile: { bio: { text: "" } },
    },
    goal: "To make money",
    id: "fd4b2962-d3eb-48cb-af6b-bd825c016264",
    last7dPnl: -12.6,
    currentPnl: -12.6,
    name: "Njoku",
    token: {
      agentId: "4",
      name: "Benjamin Bills",
      symbol: "A4",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 600,
    winRate: 100,
    active: true,
  },
];

export { dummyAgents };
