const dummyAgents: Array<Agent> = [
  {
    creator: {
      username: "ifunanya",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar1.png",
      profile: { bio: [] },
    },
    goal: "To make money",
    id: "1",
    last7dPnl: 86.7,
    name: "Favour",
    token: {
      agentId: "1",
      name: "Meister",
      symbol: "A1",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 100_000,
    winRate: 100,
  },
  {
    creator: {
      username: "ifunanya",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar2.png",
      profile: { bio: [] },
    },
    goal: "To make money",
    id: "2",
    last7dPnl: 67.9,
    name: "Justice",
    token: {
      agentId: "2",
      name: "Agent 2",
      symbol: "A2",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 5400,
    winRate: 100,
  },
  {
    creator: {
      username: "ifunanya",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar3.png",
      profile: { bio: [] },
    },
    goal: "To make money",
    id: "3",
    last7dPnl: 90.5,
    name: "Meister",
    token: {
      agentId: "3",
      name: "Agent 3",
      symbol: "A3",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 12_789,
    winRate: 100,
  },
  {
    creator: {
      username: "ifunanya",
      fid: 1,
      followers: 1_000_000,
      following: 20,
      pfp: "/images/avatar4.png",
      profile: { bio: [] },
    },
    goal: "To make money",
    id: "4",
    last7dPnl: -12.6,
    name: "Njoku",
    token: {
      agentId: "4",
      name: "Agent 4",
      symbol: "A4",
      locked: "100",
      marketCap: "100",
      status: "active",
    },
    totalPnl: 1000,
    type: "agent",
    users: 600,
    winRate: 100,
  },
];

export { dummyAgents };
